"use client";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Testimonials from "@/components/testimonials/Testimonials";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Provider } from "react-redux";
import store from "@/redux/store";
import Script from "next/script";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <ToastContainer />
          <Header />
          {children}
          <Testimonials />
          <Footer />
        </Provider>
        <Script src="https://checkout.razorpay.com/v1/checkout.js" />
      </body>
    </html>
  );
}
